### ISSUE TITLE
Installed on 1.19.2 and noticed absolutely no change. 

### ISSUE THREAD

**Issue by ebaystudio** [kikugie/techutils#15]
What does this do exactly in 1.19.2 I see the isometric previews in the later versions but nothing like that in 1.19.2

**Comment by kikugie** [comment]
That's because preview was introduced in 0.2.0 for 1.19.3

**Comment by kikugie** [comment]
Great question I can't answer. That version is there because thats what the mod used to be at that release. New updates naturally bring new features.  
Also no backports, consider 1.19.4 or 1.20 with Viafabric.

**Comment by kikugie** [comment]
Code-wise 1.19.3 brought significant changes, so much very few mods could just change the version and still work.  
Given that, I'm not going to make backports.
