### ISSUE TITLE
update to 1.20.1

### ISSUE THREAD

**Issue by DeadCourier** [kikugie/techutils#16]
I'm really looking forward to the update to 1.20.1)

**Comment by kikugie** [comment]
An early port is available at https://github.com/kikugie/techutils/actions/runs/5878748269. I'm working on a big update in the "reborn" branch, but that would be 1.20.2 instead of .1

**Comment by BrycensRanch** [comment]
> An early port is available at https://github.com/kikugie/techutils/actions/runs/5878748269. I'm working on a big update in the "reborn" branch, but that would be 1.20.2 instead of .1

me when the github actions builds have expired

**Comment by kikugie** [comment]
Consider 
![image](https://github.com/kikugie/techutils/assets/50152507/c9745098-95fc-42b5-82cb-41ffe934207c)
