### ISSUE TITLE
Litematic preview crash with Sodium 0.4.11

### ISSUE THREAD

**Issue by Oguzhan5585** [Kikugie/techutils#7]
https://mclo.gs/XRbs5Cp

**Comment by Kikugie** [comment]
I've tested this issue and it appears to be an issue with Sodium. I'll contact them to either fix it there or make a workaround in my mod.  
To temporarily fix it either disable litematic preview feature in the mod config or use [Sodium 0.4.10](https://modrinth.com/mod/sodium/version/mc1.19.4-0.4.10)

**Comment by Oguzhan5585** [comment]
aight sodium dev said that 0.4.11 is unstable, was taken down and shouldn't be used. i guess this issue is solved then since the incomaptible sodium version is not even officially downloadable anymore.
