### ISSUE TITLE
Crash when attempting to load a schematic

### ISSUE THREAD

**Issue by QPCrummer** [Kikugie/techutils#9]
Basically I just click on a schematic to load it and it will crash the game due to an OutOfBounds exception

Here are the logs: https://mclo.gs/8C3ZF8k

I don't know how much it matters, but here is the schematic: 
[30gt_Jam_proof_Bridged_B36_TNT_module_tower_x4.zip](https://github.com/Kikugie/techutils/files/11470828/30gt_Jam_proof_Bridged_B36_TNT_module_tower_x4.zip)

**Comment by Kikugie** [comment]
That is a known problem with Sodium 0.4.11, see #7
That version was taken down by Sodium devs, so pls use 0.4.10
